// **********************************************************************
// Parsed By TarsParser(1.1.0), Generated By tools(20180606)
// TarsParser Maintained By <WSRD> and tools Maintained By <superzheng>
// Generated from "PropertyPlusF.tars" by Client Mode
// **********************************************************************

"use strict";

var assert    = require("assert");
var TarsStream = require("@tars/stream");
var TarsError  = require("@tars/rpc").error;

var tars = tars || {};
module.exports.tars = tars;

tars.PropertyPlusFProxy = function () {
    this._name   = undefined;
    this._worker = undefined;
};

tars.PropertyPlusFProxy.prototype.setTimeout = function (iTimeout) {
    this._worker.timeout = iTimeout;
};

tars.PropertyPlusFProxy.prototype.getTimeout = function () {
    return this._worker.timeout;
};


tars.StatLog = function() {
    this.logname = "";
    this.content = new TarsStream.List(TarsStream.String, 1);
    this.date = "";
    this.flag = "";
    this.extend = 0;
    this._classname = "tars.StatLog";
};
tars.StatLog._classname = "tars.StatLog";
tars.StatLog._write = function (os, tag, value) { os.writeStruct(tag, value); };
tars.StatLog._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
tars.StatLog._readFrom = function (is) {
    var tmp = new tars.StatLog();
    tmp.logname = is.readString(0, true, "");
    tmp.content = is.readList(1, true, TarsStream.List(TarsStream.String, 1));
    tmp.date = is.readString(2, false, "");
    tmp.flag = is.readString(3, false, "");
    tmp.extend = is.readInt32(4, false, 0);
    return tmp;
};
tars.StatLog.prototype._writeTo = function (os) {
    os.writeString(0, this.logname);
    os.writeList(1, this.content);
    os.writeString(2, this.date);
    os.writeString(3, this.flag);
    os.writeInt32(4, this.extend);
};
tars.StatLog.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
tars.StatLog.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
tars.StatLog.prototype.toObject = function() { 
    return {
        "logname" : this.logname,
        "content" : this.content.toObject(),
        "date" : this.date,
        "flag" : this.flag,
        "extend" : this.extend
    };
};
tars.StatLog.prototype.readFromObject = function(json) { 
    json.hasOwnProperty("logname") && (this.logname = json.logname);
    json.hasOwnProperty("content") && (this.content.readFromObject(json.content));
    json.hasOwnProperty("date") && (this.date = json.date);
    json.hasOwnProperty("flag") && (this.flag = json.flag);
    json.hasOwnProperty("extend") && (this.extend = json.extend);
};
tars.StatLog.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
tars.StatLog.new = function () {
    return new tars.StatLog();
};
tars.StatLog.create = function (is) {
    return tars.StatLog._readFrom(is);
};

tars.StatValue = function() {
    this.policy = "";
    this.value = 0;
    this.count = 0;
    this._classname = "tars.StatValue";
};
tars.StatValue._classname = "tars.StatValue";
tars.StatValue._write = function (os, tag, value) { os.writeStruct(tag, value); };
tars.StatValue._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
tars.StatValue._readFrom = function (is) {
    var tmp = new tars.StatValue();
    tmp.policy = is.readString(0, true, "");
    tmp.value = is.readFloat(1, true, 0);
    tmp.count = is.readInt64(2, true, 0);
    return tmp;
};
tars.StatValue.prototype._writeTo = function (os) {
    os.writeString(0, this.policy);
    os.writeFloat(1, this.value);
    os.writeInt64(2, this.count);
};
tars.StatValue.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
tars.StatValue.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
tars.StatValue.prototype.toObject = function() { 
    return {
        "policy" : this.policy,
        "value" : this.value,
        "count" : this.count
    };
};
tars.StatValue.prototype.readFromObject = function(json) { 
    json.hasOwnProperty("policy") && (this.policy = json.policy);
    json.hasOwnProperty("value") && (this.value = json.value);
    json.hasOwnProperty("count") && (this.count = json.count);
};
tars.StatValue.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
tars.StatValue.new = function () {
    return new tars.StatValue();
};
tars.StatValue.create = function (is) {
    return tars.StatValue._readFrom(is);
};

tars.StatContent = function() {
    this.keys = new TarsStream.List(TarsStream.String);
    this.values = new TarsStream.List(tars.StatValue);
    this._classname = "tars.StatContent";
};
tars.StatContent._classname = "tars.StatContent";
tars.StatContent._write = function (os, tag, value) { os.writeStruct(tag, value); };
tars.StatContent._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
tars.StatContent._readFrom = function (is) {
    var tmp = new tars.StatContent();
    tmp.keys = is.readList(0, true, TarsStream.List(TarsStream.String));
    tmp.values = is.readList(1, true, TarsStream.List(tars.StatValue));
    return tmp;
};
tars.StatContent.prototype._writeTo = function (os) {
    os.writeList(0, this.keys);
    os.writeList(1, this.values);
};
tars.StatContent.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
tars.StatContent.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
tars.StatContent.prototype.toObject = function() { 
    return {
        "keys" : this.keys.toObject(),
        "values" : this.values.toObject()
    };
};
tars.StatContent.prototype.readFromObject = function(json) { 
    json.hasOwnProperty("keys") && (this.keys.readFromObject(json.keys));
    json.hasOwnProperty("values") && (this.values.readFromObject(json.values));
};
tars.StatContent.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
tars.StatContent.new = function () {
    return new tars.StatContent();
};
tars.StatContent.create = function (is) {
    return tars.StatContent._readFrom(is);
};

tars.StatOneLog = function() {
    this.logname = "";
    this.keys = new TarsStream.List(TarsStream.String);
    this.values = new TarsStream.List(tars.StatValue);
    this._classname = "tars.StatOneLog";
};
tars.StatOneLog._classname = "tars.StatOneLog";
tars.StatOneLog._write = function (os, tag, value) { os.writeStruct(tag, value); };
tars.StatOneLog._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
tars.StatOneLog._readFrom = function (is) {
    var tmp = new tars.StatOneLog();
    tmp.logname = is.readString(0, true, "");
    tmp.keys = is.readList(1, true, TarsStream.List(TarsStream.String));
    tmp.values = is.readList(2, true, TarsStream.List(tars.StatValue));
    return tmp;
};
tars.StatOneLog.prototype._writeTo = function (os) {
    os.writeString(0, this.logname);
    os.writeList(1, this.keys);
    os.writeList(2, this.values);
};
tars.StatOneLog.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
tars.StatOneLog.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
tars.StatOneLog.prototype.toObject = function() { 
    return {
        "logname" : this.logname,
        "keys" : this.keys.toObject(),
        "values" : this.values.toObject()
    };
};
tars.StatOneLog.prototype.readFromObject = function(json) { 
    json.hasOwnProperty("logname") && (this.logname = json.logname);
    json.hasOwnProperty("keys") && (this.keys.readFromObject(json.keys));
    json.hasOwnProperty("values") && (this.values.readFromObject(json.values));
};
tars.StatOneLog.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
tars.StatOneLog.new = function () {
    return new tars.StatOneLog();
};
tars.StatOneLog.create = function (is) {
    return tars.StatOneLog._readFrom(is);
};


var __tars_PropertyPlusF$logstat$EN = function (log) {
    var os = new TarsStream.TarsOutputStream();
    os.writeStruct(1, log);
    return os.getBinBuffer();
};

var __tars_PropertyPlusF$logstat$DE = function (data) {
    try {
        var is = new TarsStream.TarsInputStream(data.response.sBuffer);
        return {
            "request" : data.request,
            "response" : {
                "costtime" : data.request.costtime,
                "return" : is.readInt32(0, true, 0)
            }
        };
    } catch (e) {
        throw {
            "request" : data.request,
            "response" : {
                "costtime" : data.request.costtime,
                "error" : {
                    "code" : TarsError.CLIENT.DECODE_ERROR,
                    "message" : e.message
                }
            }
        };
    }
};

var __tars_PropertyPlusF$logstat$ER = function (data) {
    throw {
        "request" : data.request,
        "response" : {
            "costtime" : data.request.costtime,
            "error" : data.error
        }
    }
};

tars.PropertyPlusFProxy.prototype.logstat = function (log) {
    return this._worker.tars_invoke("logstat", __tars_PropertyPlusF$logstat$EN(log), arguments[arguments.length - 1]).then(__tars_PropertyPlusF$logstat$DE, __tars_PropertyPlusF$logstat$ER);
};

var __tars_PropertyPlusF$mutillogstat$EN = function (logs) {
    var os = new TarsStream.TarsOutputStream();
    os.writeList(1, logs);
    return os.getBinBuffer();
};

var __tars_PropertyPlusF$mutillogstat$DE = function (data) {
    try {
        var is = new TarsStream.TarsInputStream(data.response.sBuffer);
        return {
            "request" : data.request,
            "response" : {
                "costtime" : data.request.costtime,
                "return" : is.readInt32(0, true, 0)
            }
        };
    } catch (e) {
        throw {
            "request" : data.request,
            "response" : {
                "costtime" : data.request.costtime,
                "error" : {
                    "code" : TarsError.CLIENT.DECODE_ERROR,
                    "message" : e.message
                }
            }
        };
    }
};

var __tars_PropertyPlusF$mutillogstat$ER = function (data) {
    throw {
        "request" : data.request,
        "response" : {
            "costtime" : data.request.costtime,
            "error" : data.error
        }
    }
};

tars.PropertyPlusFProxy.prototype.mutillogstat = function (logs) {
    return this._worker.tars_invoke("mutillogstat", __tars_PropertyPlusF$mutillogstat$EN(logs), arguments[arguments.length - 1]).then(__tars_PropertyPlusF$mutillogstat$DE, __tars_PropertyPlusF$mutillogstat$ER);
};



